const NUMBERS = "0123456789";
const LATINLOWERCASE = "abcdefghijklmnopqrstuvwxyz";
const LATINUPPERCASE = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
const SPECIAL = " !\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~";
const ALLCHARSETS = NUMBERS + LATINLOWERCASE + LATINUPPERCASE + SPECIAL;

module.exports = {
  NUMBERS,
  LATINLOWERCASE,
  LATINUPPERCASE,
  SPECIAL,
  ALLCHARSETS,
};

